### ISSUE TITLE
Issue while doing ng build --prod on Angular 4.2.4

### ISSUE THREAD

**Issue by shishiroars** [web-dave/ngx-img-cropper#40]
On running ng build --prod, I'm getting below error :

ERROR in Error: Unexpected value 'ImageCropperComponent in /Users/shishir/Documents/Github/dummyProj/node_modules/ngx-img-cropper/src/imageCropperComponent.d.ts' declared by the module 'SharedModule in /Users/shishir/Documents/Github/dummyProj/src/app/shared/shared.module.ts'. Please add a @Pipe/@Directive/@component annotation.
at syntaxError (/Users/shishir/Documents/Github/dummyProj/node_modules//bundles/compiler.umd.js:1729:34)
at /Users/shishir/Documents/Github/dummyProj/node_modules//bundles/compiler.umd.js:15481:40
at Array.forEach ()
at CompileMetadataResolver.getNgModuleMetadata (/Users/shishir/Documents/Github/dummyProj/node_modules//bundles/compiler.umd.js:15463:54)
at addNgModule (/Users/shishir/Documents/Github/dummyProj/node_modules//bundles/compiler.umd.js:24268:58)
at /Users/shishir/Documents/Github/dummyProj/node_modules//bundles/compiler.umd.js:24279:14
at Array.forEach ()
at _createNgModules (/Users/shishir/Documents/Github/dummyProj/node_modules//bundles/compiler.umd.js:24278:26)
at analyzeNgModules (/Users/shishir/Documents/Github/dummyProj/node_modules//bundles/compiler.umd.js:24153:14)
at analyzeAndValidateNgModules (/Users/shishir/Documents/Github/dummyProj/node_modules//bundles/compiler.umd.js:24163:35)
at AotCompiler.analyzeModulesAsync (/Users/shishir/Documents/Github/dummyProj/node_modules//bundles/compiler.umd.js:23797:46)
at CodeGenerator.codegen (/Users/shishir/Documents/Github/dummyProj/node_modules//src/codegen.js:32:14)
at Function.NgTools_InternalApi_NG_2.codeGen (/Users/shishir/Documents/Github/dummyProj/node_modules//src/ngtools_api.js:73:30)
at _donePromise.Promise.resolve.then (/Users/shishir/Documents/Github/dummyProj/node_modules//src/plugin.js:391:44)
at 
at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Raul6469** [comment]
I'm running through the same issue, did you manage to solve this problem?

**Comment by web-dave** [comment]
Fixed in new version (7.0.5)
