### ISSUE TITLE
SSR: Image is not defined

### ISSUE THREAD

**Issue by nimatrazmjo** [web-dave/ngx-img-cropper#83]
Hi, with Angular Universal, I receive this error.

```
2019-11-16 13:48 +04:30: ERROR ReferenceError: Image is not defined
    at new ImageCropper (/var/www/app/jobsaf-website/public/web/server.js:397231:34)
    at ImageCropperComponent.ngAfterViewInit (/var/www/app/jobsaf-website/public/web/server.js:398968:28)
    at callProviderLifecycles (/var/www/app/jobsaf-website/public/web/server.js:21972:18)
    at callElementProvidersLifecycles (/var/www/app/jobsaf-website/public/web/server.js:21946:13)
    at callLifecycleHooksChildrenFirst (/var/www/app/jobsaf-website/public/web/server.js:21936:29)
    at checkAndUpdateView (/var/www/app/jobsaf-website/public/web/server.js:30006:5)
    at callViewAction (/var/www/app/jobsaf-website/public/web/server.js:30238:21)
    at execEmbeddedViewsAction (/var/www/app/jobsaf-website/public/web/server.js:30201:17)
    at checkAndUpdateView (/var/www/app/jobsaf-website/public/web/server.js:29998:5)
    at callViewAction (/var/www/app/jobsaf-website/public/web/server.js:30238:21)
    at execComponentViewsAction (/var/www/app/jobsaf-website/public/web/server.js:30180:13)
    at checkAndUpdateView (/var/www/app/jobsaf-website/public/web/server.js:30003:5)
    at callViewAction (/var/www/app/jobsaf-website/public/web/server.js:30238:21)
    at execEmbeddedViewsAction (/var/www/app/jobsaf-website/public/web/server.js:30201:17)
    at checkAndUpdateView (/var/www/app/jobsaf-website/public/web/server.js:29998:5)
    at callViewAction (/var/www/app/jobsaf-website/public/web/server.js:30238:21)
    at execComponentViewsAction (/var/www/app/jobsaf-website/public/web/server.js:30180:13)
    at checkAndUpdateView (/var/www/app/jobsaf-website/public/web/server.js:30003:5)
    at callViewAction (/var/www/app/jobsaf-website/public/web/server.js:30238:21)
    at execEmbeddedViewsAction (/var/www/app/jobsaf-website/public/web/server.js:30201:17)
    at checkAndUpdateView (/var/www/app/jobsaf-website/public/web/server.js:29998:5)
    at callViewAction (/var/www/app/jobsaf-website/public/web/server.js:30238:21)
    at execComponentViewsAction (/var/www/app/jobsaf-website/public/web/server.js:30180:13)
    at checkAndUpdateView (/var/www/app/jobsaf-website/public/web/server.js:30003:5)
    at callViewAction (/var/www/app/jobsaf-website/public/web/server.js:30238:21)
    at execEmbeddedViewsAction (/var/www/app/jobsaf-website/public/web/server.js:30201:17)
    at checkAndUpdateView (/var/www/app/jobsaf-website/public/web/server.js:29998:5)
    at callViewAction (/var/www/app/jobsaf-website/public/web/server.js:30238:21)
```

How I define in my component:

      addCoverCropper: ImageCropperComponent;

My question is how can I avoid it with SSR.

**Comment by nimatullah** [comment]
@davidbonachera can you please look at this.

**Comment by web-dave** [comment]
This issue has been automatically closed due to  inactivity. Thank you for your contributions.
